## Data Cleaning and Wrangling for COVID Personal Project
---

In [1]:
#to import necessary libraries
import numpy as np
import pandas as pd

In [2]:
#to load the dataset
file_path = "/Users/srinidhi/Desktop/COVID_Project/CovidSG_Dataset.xlsx" 

df1 = pd.read_excel(file_path, sheet_name=0)
df2 = pd.read_excel(file_path, sheet_name=1)
df3 = pd.read_excel(file_path, sheet_name=2)

cases_df = df1.copy()
death_df  = df2.copy()
profiles_df = df3.copy()

### 1) Cleaning of First DataFrame - based on Covid Trends

In [3]:
#to display the first few rows of the 'cases_df' DataFrame
cases_df.head()

,Date,Daily Confirmed,False Positives Found,Cumulative Confirmed,Daily Discharged,Passed but not due to COVID,Cumulative Discharged,Discharged to Isolation,Still Hospitalised,Daily Deaths,...,Cumulative Individuals Vaccinated,Cumulative Individuals Vaccination Completed,Perc population completed at least one dose,Perc population completed vaccination,Sinovac vaccine doses,Cumulative individuals using Sinovac vaccine,Doses of other vaccines recognised by WHO,Cumulative individuals using other vaccines recognised by WHO,Number taken booster shots,Perc population taken booster shots
0,2020-01-23,1.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-24,2.0,NaN,3.0,0.0,0.0,0.0,0.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-25,1.0,NaN,4.0,0.0,0.0,0.0,0.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-26,0.0,NaN,4.0,0.0,0.0,0.0,0.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-27,1.0,NaN,5.0,0.0,0.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#to show the size of the dataset (number of rows and columns)
print(cases_df.shape) 

 #to show the type and number of columns
print(cases_df.columns)

(1023, 36)
Index(['Date', 'Daily Confirmed', 'False Positives Found',
       'Cumulative Confirmed', 'Daily Discharged',
       'Passed but not due to COVID', 'Cumulative Discharged',
       'Discharged to Isolation', 'Still Hospitalised', 'Daily Deaths',
       'Cumulative Deaths', 'Tested positive demise', 'Daily Imported',
       'Daily Local transmission', 'Local cases residing in dorms MOH report',
       'Local cases not residing in doms MOH report',
       'Intensive Care Unit (ICU)', 'General Wards MOH report',
       'In Isolation MOH report', 'Total Completed Isolation MOH report',
       'Total Hospital Discharged MOH report',
       'Requires Oxygen Supplementation or Unstable', 'Linked community cases',
       'Unlinked community cases', 'Phase', 'Cumulative Vaccine Doses',
       'Cumulative Individuals Vaccinated',
       'Cumulative Individuals Vaccination Completed',
       'Perc population completed at least one dose',
       'Perc population completed vaccination', 'Sinovac vaccine doses',
       'Cumulative individuals using Sinovac vaccine',
       'Doses of other vaccines recognised by WHO',
       'Cumulative individuals using other vaccines recognised by WHO',
       'Number taken booster shots', 'Perc population taken booster shots'],
      dtype='object')

In [5]:
#to capitalize and standardize the column names of the DataFrame
cases_df.columns = cases_df.columns.str.capitalize()

In [6]:
# to view data types of the columns in the DataFrame
cases_df.dtypes

Date                                                              object
Daily confirmed                                                  float64
False positives found                                            float64
Cumulative confirmed                                             float64
Daily discharged                                                 float64
Passed but not due to covid                                      float64
Cumulative discharged                                            float64
Discharged to isolation                                          float64
Still hospitalised                                               float64
Daily deaths                                                     float64
Cumulative deaths                                                float64
Tested positive demise                                           float64
Daily imported                                                   float64
Daily local transmission                                         float64
Local cases residing in dorms moh report                         float64
Local cases not residing in doms moh report                      float64
Intensive care unit (icu)                                        float64
General wards moh report                                         float64
In isolation moh report                                          float64
Total completed isolation moh report                             float64
Total hospital discharged moh report                             float64
Requires oxygen supplementation or unstable                      float64
Linked community cases                                           float64
Unlinked community cases                                         float64
Phase                                                             object
Cumulative vaccine doses                                         float64
Cumulative individuals vaccinated                                float64
Cumulative individuals vaccination completed                     float64
Perc population completed at least one dose                      float64
Perc population completed vaccination                            float64
Sinovac vaccine doses                                            float64
Cumulative individuals using sinovac vaccine                     float64
Doses of other vaccines recognised by who                        float64
Cumulative individuals using other vaccines recognised by who    float64
Number taken booster shots                                       float64
Perc population taken booster shots                              float64
dtype: object

In [7]:
#to convert date column from object to datetime type
cases_df['Date'] = pd.to_datetime(cases_df['Date'])

In [8]:
#to select numerical and categorical variables
numerical_columns1 = cases_df.select_dtypes(include=[int,float]).columns
categorical_columns1 = cases_df.select_dtypes('object').columns
datetime_columns1 = cases_df.select_dtypes('datetime').columns

#to count the number of numerical and categorical variables
print(len(numerical_columns1)) 
print(len(categorical_columns1))
print(len(datetime_columns1))

34
1
1

In [9]:
#to calculate the false positive rate
false_positives = cases_df['False positives found'].sum(skipna=True) / cases_df['Daily confirmed'].sum(skipna=True)
print('False positive rate: ', false_positives)

False positive rate:  4.1195853843289944e-05

In [10]:
#to check for missing values for each column
cases_df.isnull().sum()

Date                                                                1
Daily confirmed                                                    57
False positives found                                             326
Cumulative confirmed                                               56
Daily discharged                                                  136
Passed but not due to covid                                       217
Cumulative discharged                                             233
Discharged to isolation                                           231
Still hospitalised                                                233
Daily deaths                                                      101
Cumulative deaths                                                  99
Tested positive demise                                            217
Daily imported                                                     59
Daily local transmission                                            5
Local cases residing in dorms moh report                          283
Local cases not residing in doms moh report                       283
Intensive care unit (icu)                                          54
General wards moh report                                          290
In isolation moh report                                           290
Total completed isolation moh report                              291
Total hospital discharged moh report                              291
Requires oxygen supplementation or unstable                       556
Linked community cases                                            863
Unlinked community cases                                          863
Phase                                                              80
Cumulative vaccine doses                                          903
Cumulative individuals vaccinated                                 903
Cumulative individuals vaccination completed                      903
Perc population completed at least one dose                       561
Perc population completed vaccination                             565
Sinovac vaccine doses                                            1014
Cumulative individuals using sinovac vaccine                     1014
Doses of other vaccines recognised by who                         943
Cumulative individuals using other vaccines recognised by who     943
Number taken booster shots                                        992
Perc population taken booster shots                               743
dtype: int64

In [11]:
#to drop any missing values for our two most important columns for analysis
cases_df.dropna(subset=['Date', 'Daily confirmed'], inplace=True)

In [12]:
#to check for changes in missing values for each column
cases_df.isnull().sum()

Date                                                               0
Daily confirmed                                                    0
False positives found                                            269
Cumulative confirmed                                               0
Daily discharged                                                  80
Passed but not due to covid                                      160
Cumulative discharged                                            176
Discharged to isolation                                          174
Still hospitalised                                               176
Daily deaths                                                      46
Cumulative deaths                                                 44
Tested positive demise                                           160
Daily imported                                                     2
Daily local transmission                                           2
Local cases residing in dorms moh report                         226
Local cases not residing in doms moh report                      226
Intensive care unit (icu)                                          0
General wards moh report                                         233
In isolation moh report                                          233
Total completed isolation moh report                             234
Total hospital discharged moh report                             234
Requires oxygen supplementation or unstable                      504
Linked community cases                                           806
Unlinked community cases                                         806
Phase                                                             77
Cumulative vaccine doses                                         846
Cumulative individuals vaccinated                                846
Cumulative individuals vaccination completed                     846
Perc population completed at least one dose                      558
Perc population completed vaccination                            562
Sinovac vaccine doses                                            957
Cumulative individuals using sinovac vaccine                     957
Doses of other vaccines recognised by who                        886
Cumulative individuals using other vaccines recognised by who    886
Number taken booster shots                                       935
Perc population taken booster shots                              686
dtype: int64

In [13]:
cases_df.head()

,Date,Daily confirmed,False positives found,Cumulative confirmed,Daily discharged,Passed but not due to covid,Cumulative discharged,Discharged to isolation,Still hospitalised,Daily deaths,...,Cumulative individuals vaccinated,Cumulative individuals vaccination completed,Perc population completed at least one dose,Perc population completed vaccination,Sinovac vaccine doses,Cumulative individuals using sinovac vaccine,Doses of other vaccines recognised by who,Cumulative individuals using other vaccines recognised by who,Number taken booster shots,Perc population taken booster shots
0,2020-01-23,1.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-24,2.0,NaN,3.0,0.0,0.0,0.0,0.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-25,1.0,NaN,4.0,0.0,0.0,0.0,0.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-26,0.0,NaN,4.0,0.0,0.0,0.0,0.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-27,1.0,NaN,5.0,0.0,0.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#to drop the columns related to vaccination as we are not focusing on it for our analysis
cases_df.drop(cases_df.columns[25:36], axis=1, inplace=True)
cases_df.head()

,Date,Daily confirmed,False positives found,Cumulative confirmed,Daily discharged,Passed but not due to covid,Cumulative discharged,Discharged to isolation,Still hospitalised,Daily deaths,...,Local cases not residing in doms moh report,Intensive care unit (icu),General wards moh report,In isolation moh report,Total completed isolation moh report,Total hospital discharged moh report,Requires oxygen supplementation or unstable,Linked community cases,Unlinked community cases,Phase
0,2020-01-23,1.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-24,2.0,NaN,3.0,0.0,0.0,0.0,0.0,3.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-25,1.0,NaN,4.0,0.0,0.0,0.0,0.0,4.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-26,0.0,NaN,4.0,0.0,0.0,0.0,0.0,4.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-27,1.0,NaN,5.0,0.0,0.0,0.0,0.0,5.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#to drop other columns that would not be meaningful for analysis (either because they are not needed or have a lot of missing values)
cases_df.drop(['False positives found', 'Passed but not due to covid', 'Discharged to isolation', 'Tested positive demise', 'General wards moh report', 'In isolation moh report', 'Total completed isolation moh report', 'Total hospital discharged moh report' , 'Requires oxygen supplementation or unstable'], axis=1, inplace=True)

In [16]:
#to check for missing values for each column again
cases_df.isnull().sum()

Date                                             0
Daily confirmed                                  0
Cumulative confirmed                             0
Daily discharged                                80
Cumulative discharged                          176
Still hospitalised                             176
Daily deaths                                    46
Cumulative deaths                               44
Daily imported                                   2
Daily local transmission                         2
Local cases residing in dorms moh report       226
Local cases not residing in doms moh report    226
Intensive care unit (icu)                        0
Linked community cases                         806
Unlinked community cases                       806
Phase                                           77
dtype: int64

In [18]:
#to filter the rows and include only those with dates in the year 2020 and 2021
cases_df_fil = cases_df[(cases_df['Date'].dt.year >= 2020) & (cases_df['Date'].dt.year <= 2021)]

In [19]:
#to check for missing values for each column again
cases_df_fil.isnull().sum()

Date                                             0
Daily confirmed                                  0
Cumulative confirmed                             0
Daily discharged                                 0
Cumulative discharged                            0
Still hospitalised                               0
Daily deaths                                     0
Cumulative deaths                                0
Daily imported                                   0
Daily local transmission                         0
Local cases residing in dorms moh report        66
Local cases not residing in doms moh report     66
Intensive care unit (icu)                        0
Linked community cases                         549
Unlinked community cases                       549
Phase                                           75
dtype: int64

In [20]:
#to fill the missing data for 'Phase' variable
cases_df_fil.loc[:, 'Phase'] = cases_df_fil['Phase'].fillna('No Phase')

In [21]:
cases_df_fil.head()

,Date,Daily confirmed,Cumulative confirmed,Daily discharged,Cumulative discharged,Still hospitalised,Daily deaths,Cumulative deaths,Daily imported,Daily local transmission,Local cases residing in dorms moh report,Local cases not residing in doms moh report,Intensive care unit (icu),Linked community cases,Unlinked community cases,Phase
0,2020-01-23,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,No Phase
1,2020-01-24,2.0,3.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,NaN,NaN,0.0,NaN,NaN,No Phase
2,2020-01-25,1.0,4.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,No Phase
3,2020-01-26,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,No Phase
4,2020-01-27,1.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,No Phase

In [22]:
#to ensure sub-variables related to "Daily Local Transmission" are zero when the main variable is zero (i.e. all the variables stated below are subsets of "Daily Local Transmission")
cases_df_fil.loc[cases_df_fil['Daily local transmission'] == 0, ['Local cases residing in dorms moh report', 'Local cases not residing in doms moh report', 'Linked community cases', 'Unlinked community cases']] = 0

In [23]:
cases_df_fil.head()

,Date,Daily confirmed,Cumulative confirmed,Daily discharged,Cumulative discharged,Still hospitalised,Daily deaths,Cumulative deaths,Daily imported,Daily local transmission,Local cases residing in dorms moh report,Local cases not residing in doms moh report,Intensive care unit (icu),Linked community cases,Unlinked community cases,Phase
0,2020-01-23,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase
1,2020-01-24,2.0,3.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase
2,2020-01-25,1.0,4.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase
3,2020-01-26,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase
4,2020-01-27,1.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase

In [24]:
cases_df_fil.isnull().sum()

Date                                             0
Daily confirmed                                  0
Cumulative confirmed                             0
Daily discharged                                 0
Cumulative discharged                            0
Still hospitalised                               0
Daily deaths                                     0
Cumulative deaths                                0
Daily imported                                   0
Daily local transmission                         0
Local cases residing in dorms moh report        53
Local cases not residing in doms moh report     53
Intensive care unit (icu)                        0
Linked community cases                         431
Unlinked community cases                       431
Phase                                            0
dtype: int64

In [25]:
cases_df_fil.shape

(709, 16)

Observed some discrepancies where the addition of  "Local cases residing in dorms moh report" and "Local cases not residing in doms moh report", does not tally with the "Daily local transmission". Hence, we will be creating a new variable to cross-check, and rectify the discrepancies.

In [26]:
#to create a new variable to calculate the total local transmission cases
cases_df_fil.loc[:, 'calc_localtransmission'] = pd.to_numeric(cases_df_fil['Local cases residing in dorms moh report'], errors='coerce').fillna(pd.NA) + pd.to_numeric(cases_df_fil['Local cases not residing in doms moh report'], errors='coerce').fillna(pd.NA)

<ipython-input-26-1cacba569a1a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cases_df_fil.loc[:, 'calc_localtransmission'] = pd.to_numeric(cases_df_fil['Local cases residing in dorms moh report'], errors='coerce').fillna(pd.NA) + pd.to_numeric(cases_df_fil['Local cases not residing in doms moh report'], errors='coerce').fillna(pd.NA)

In [27]:
cases_df_fil.head()

,Date,Daily confirmed,Cumulative confirmed,Daily discharged,Cumulative discharged,Still hospitalised,Daily deaths,Cumulative deaths,Daily imported,Daily local transmission,Local cases residing in dorms moh report,Local cases not residing in doms moh report,Intensive care unit (icu),Linked community cases,Unlinked community cases,Phase,calc_localtransmission
0,2020-01-23,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase,0.0
1,2020-01-24,2.0,3.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase,0.0
2,2020-01-25,1.0,4.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase,0.0
3,2020-01-26,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase,0.0
4,2020-01-27,1.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,No Phase,0.0

In [28]:
cases_df_fil.tail()

,Date,Daily confirmed,Cumulative confirmed,Daily discharged,Cumulative discharged,Still hospitalised,Daily deaths,Cumulative deaths,Daily imported,Daily local transmission,Local cases residing in dorms moh report,Local cases not residing in doms moh report,Intensive care unit (icu),Linked community cases,Unlinked community cases,Phase,calc_localtransmission
704,2021-12-27,280.0,278044.0,319.0,274545.0,333.0,3.0,825.0,134.0,146.0,5.0,141.0,17.0,NaN,NaN,Transition Phase,146.0
705,2021-12-28,365.0,278409.0,285.0,274830.0,273.0,0.0,825.0,173.0,192.0,1.0,191.0,17.0,NaN,NaN,Transition Phase,192.0
706,2021-12-29,341.0,278750.0,276.0,275106.0,275.0,1.0,826.0,153.0,188.0,6.0,182.0,16.0,NaN,NaN,Transition Phase,188.0
707,2021-12-30,311.0,279061.0,273.0,275379.0,249.0,1.0,827.0,114.0,197.0,4.0,193.0,16.0,NaN,NaN,Transition Phase,197.0
708,2021-12-31,344.0,279405.0,352.0,275731.0,236.0,1.0,828.0,172.0,172.0,7.0,165.0,16.0,NaN,NaN,Transition Phase,172.0

In [29]:
#to calculate the number of discrepancies when our calculated value does not tally with the dataset value
mismatch_rows = cases_df_fil[(cases_df_fil['Daily local transmission'].notna()) & (cases_df_fil['calc_localtransmission'].notna()) & (cases_df_fil['Daily local transmission'] != cases_df_fil['calc_localtransmission'])]
count_mismatch = len(mismatch_rows)
print(count_mismatch)

4

In [30]:
#to print the rows of the mismatch data where "Daily local transmission" does not tally with "calc_localtransmission"
mismatch_df = mismatch_rows.loc[:, ['Date', 'Daily local transmission', 'Local cases residing in dorms moh report', 'Local cases not residing in doms moh report', 'calc_localtransmission']]
mismatch_df.head()

,Date,Daily local transmission,Local cases residing in dorms moh report,Local cases not residing in doms moh report,calc_localtransmission
66,2020-03-29,18.0,2.0,17.0,19.0
67,2020-03-30,26.0,3.0,22.0,25.0
72,2020-04-04,69.0,23.0,45.0,68.0
239,2020-09-18,10.0,9.0,0.0,9.0

For the purpose of our analysis, we are going to assume that the "Local cases residing in dorms moh report" and "Local cases not residing in doms moh report" has no errors. This would mean that the "calc_localtransmission" is accurate metric, and we would be using that as a standard to rectify the actual "Daily local transmission" data

In [31]:
#to rectify the discrepancies for each mismatch data
cases_df_fil.loc[[66], 'Daily local transmission'] += 1
cases_df_fil.loc[[67, 72, 239], 'Daily local transmission'] -= 1

In [32]:
#to recalculate the mismatch data and ensure we have corrected all errors
mismatch_rows = cases_df_fil[(cases_df_fil['Daily local transmission'].notna()) & (cases_df_fil['calc_localtransmission'].notna()) & (cases_df_fil['Daily local transmission'] != cases_df_fil['calc_localtransmission'])]
count_mismatch = len(mismatch_rows)
print(count_mismatch)

0

For the remaining missing values in "Local cases not residing in doms moh report" and "Local cases residing in dorms moh report", we are going to use the "Daily local transmission" variable to fill in. 

Based on research, we know that new cases that were formed in 2020 were only at foreign worker dormitories while local cases only started forming the bulk of new cases from April 2021. Since all the missing data is for the 2020 period, we are going to assume that all non-dorm cases will be zero (i.e. variable "Local cases not residing in doms moh report" set to 0) and all dorm cases is equal to the local cases (i.e. variable "Local cases residing in dorms moh report set to same value as "Daily local transmission").

In [33]:
#to fill proxy values for missing data for dorms and non-dorm cases
cases_df_fil.loc[:, 'Local cases not residing in doms moh report'] = cases_df_fil['Local cases not residing in doms moh report'].fillna(0)
cases_df_fil.loc[:, 'Local cases residing in dorms moh report'] = cases_df_fil['Local cases residing in dorms moh report'].fillna(cases_df_fil['Daily local transmission'])

In [34]:
cases_df_fil.tail()

,Date,Daily confirmed,Cumulative confirmed,Daily discharged,Cumulative discharged,Still hospitalised,Daily deaths,Cumulative deaths,Daily imported,Daily local transmission,Local cases residing in dorms moh report,Local cases not residing in doms moh report,Intensive care unit (icu),Linked community cases,Unlinked community cases,Phase,calc_localtransmission
704,2021-12-27,280.0,278044.0,319.0,274545.0,333.0,3.0,825.0,134.0,146.0,5.0,141.0,17.0,NaN,NaN,Transition Phase,146.0
705,2021-12-28,365.0,278409.0,285.0,274830.0,273.0,0.0,825.0,173.0,192.0,1.0,191.0,17.0,NaN,NaN,Transition Phase,192.0
706,2021-12-29,341.0,278750.0,276.0,275106.0,275.0,1.0,826.0,153.0,188.0,6.0,182.0,16.0,NaN,NaN,Transition Phase,188.0
707,2021-12-30,311.0,279061.0,273.0,275379.0,249.0,1.0,827.0,114.0,197.0,4.0,193.0,16.0,NaN,NaN,Transition Phase,197.0
708,2021-12-31,344.0,279405.0,352.0,275731.0,236.0,1.0,828.0,172.0,172.0,7.0,165.0,16.0,NaN,NaN,Transition Phase,172.0

In [35]:
#drop the calculated value, since the errors have been rectified
cases_df_fil.drop('calc_localtransmission', axis=1, inplace=True)

<ipython-input-35-72e6eecc05d9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cases_df_fil.drop('calc_localtransmission', axis=1, inplace=True)

In [36]:
#to rename the columns for easier reference
cases_df_fil = cases_df_fil.copy()
cases_df_fil.rename(columns={'Local cases residing in dorms moh report': 'Local Dorm Cases'}, inplace=True)
cases_df_fil.rename(columns={'Local cases not residing in doms moh report': 'Local Community Cases'}, inplace=True)

In [37]:
#to fill the missing values with NA since there is no proxy we can use for this
cases_df_fil['Linked community cases'].fillna("NA", inplace=True)
cases_df_fil['Unlinked community cases'].fillna("NA", inplace=True)

In [38]:
cases_df_fil.isnull().sum()

Date                         0
Daily confirmed              0
Cumulative confirmed         0
Daily discharged             0
Cumulative discharged        0
Still hospitalised           0
Daily deaths                 0
Cumulative deaths            0
Daily imported               0
Daily local transmission     0
Local Dorm Cases             0
Local Community Cases        0
Intensive care unit (icu)    0
Linked community cases       0
Unlinked community cases     0
Phase                        0
dtype: int64

In [39]:
#to change data type of numerical columns from float to integer
num_cols = cases_df_fil.select_dtypes(include=['float']).columns
cases_df_fil[num_cols] = cases_df_fil[num_cols].astype(int)

In [40]:
cases_df_fil.head()

,Date,Daily confirmed,Cumulative confirmed,Daily discharged,Cumulative discharged,Still hospitalised,Daily deaths,Cumulative deaths,Daily imported,Daily local transmission,Local Dorm Cases,Local Community Cases,Intensive care unit (icu),Linked community cases,Unlinked community cases,Phase
0,2020-01-23,1,1,0,0,1,0,0,1,0,0,0,0,0.0,0.0,No Phase
1,2020-01-24,2,3,0,0,3,0,0,2,0,0,0,0,0.0,0.0,No Phase
2,2020-01-25,1,4,0,0,4,0,0,1,0,0,0,0,0.0,0.0,No Phase
3,2020-01-26,0,4,0,0,4,0,0,0,0,0,0,0,0.0,0.0,No Phase
4,2020-01-27,1,5,0,0,5,0,0,1,0,0,0,0,0.0,0.0,No Phase

In [41]:
#to rename dataframe 
df_cases = cases_df_fil.copy()

In [42]:
#to see the changes in the size of dataframe before and after cleaning
print(df1.shape)
print()
print(cases_df_fil.shape)
print()
diff_rows = df1.shape[0] - df_cases.shape[0]
print(diff_rows)
print()
diff_cols = df1.shape[1] - df_cases.shape[1]
print(diff_cols)

(1023, 36)

(709, 16)

314

20

### 2) Cleaning of Second DataFrame - based on the profiles of Deaths Cases

In [43]:
#to display the first few rows of the 'death_df' DataFrame
death_df.head()

,case,date_death,date_death_pr,date_positive,date_pr,age,gender,nationality,citizenship,hospital,vaccine_no_dose,medical_history
0,90,2020-03-21,2020-03-21,2020-02-16,2020-02-16,75,F,Singapore,Citizen,NCID,0.0,"chronic heart disease, hypertension"
1,212,2020-03-21,2020-03-21,2020-03-14,2020-03-14,64,M,Indonesia,Foreigner,NCID,0.0,heart disease
2,109,2020-03-29,2020-03-29,2020-03-02,2020-03-03,70,M,Singapore,Citizen,SGH,0.0,"hypertension, hyperlipidaemia"
3,476,2020-04-02,2020-04-02,2020-03-22,2020-03-23,68,M,Indonesia,Foreigner,NCID,0.0,"diabetes, hypertension"
4,918,2020-04-03,2020-04-03,2020-03-31,2020-03-31,86,F,Singapore,Citizen,NCID,0.0,NaN

In [44]:
#to show the size of the dataset (number of rows and columns)
print(death_df.shape) 

#to show the type and number of columns
print(death_df.columns)

(85, 12)
Index(['case', 'date_death', 'date_death_pr', 'date_positive', 'date_pr',
       'age', 'gender', 'nationality', 'citizenship', 'hospital',
       'vaccine_no_dose', 'medical_history'],
      dtype='object')

In [45]:
#to capitalize and standardize the column names of the DataFrame
death_df.columns = death_df.columns.str.capitalize()

In [46]:
# to view data types of the columns in the DataFrame
death_df.dtypes

Case                        int64
Date_death         datetime64[ns]
Date_death_pr      datetime64[ns]
Date_positive      datetime64[ns]
Date_pr            datetime64[ns]
Age                         int64
Gender                     object
Nationality                object
Citizenship                object
Hospital                   object
Vaccine_no_dose           float64
Medical_history            object
dtype: object

In [47]:
#to select numerical and categorical variables
numerical_columns3 = death_df.select_dtypes(include=[int,float]).columns
categorical_columns3 = death_df.select_dtypes('object').columns
datetime_columns3 = death_df.select_dtypes('datetime').columns

#to count the number of numerical and categorical variables
print(len(numerical_columns3)) 
print(len(categorical_columns3))
print(len(datetime_columns3 ))

3
5
4

In [48]:
#to filter the rows and include only those with dates in the year 2020 and 2021
death_df_fil = death_df[(death_df['Date_death'].dt.year >= 2020) & (death_df['Date_death'].dt.year <= 2021)]

In [49]:
#to check for missing values for each column again
death_df_fil.isnull().sum()

Case                0
Date_death          0
Date_death_pr       0
Date_positive       1
Date_pr            40
Age                 0
Gender              0
Nationality         0
Citizenship         0
Hospital           16
Vaccine_no_dose     0
Medical_history    16
dtype: int64

In [50]:
#to drop other columns that would not be meaningful for analysis (either because they are not needed or have a lot of missing values)
death_df_fil = death_df_fil.drop(['Date_death_pr', 'Date_pr', 'Hospital'], axis=1)

In [51]:
death_df_fil.isnull().sum()

Case                0
Date_death          0
Date_positive       1
Age                 0
Gender              0
Nationality         0
Citizenship         0
Vaccine_no_dose     0
Medical_history    16
dtype: int64

In [52]:
#to print the rows with missing data to see if there is anything we can do to rectify
missing_rows = death_df_fil[death_df_fil.isnull().any(axis=1)]
missing_rows_df = pd.DataFrame(missing_rows)
missing_rows_df

,Case,Date_death,Date_positive,Age,Gender,Nationality,Citizenship,Vaccine_no_dose,Medical_history
4,918,2020-04-03,2020-03-31,86,F,Singapore,Citizen,0.0,NaN
6,987,2020-04-09,2020-04-01,86,F,Singapore,Citizen,0.0,NaN
7,1142,2020-04-11,2020-04-03,90,M,Singapore,Citizen,0.0,NaN
8,1836,2020-04-13,2020-04-09,65,M,Singapore,Citizen,0.0,NaN
9,128,2020-04-14,2020-03-06,70,M,Singapore,Citizen,0.0,NaN
10,3145,2020-04-17,2020-04-13,95,M,Singapore,Citizen,0.0,NaN
11,1071,2020-04-21,2020-04-02,84,F,Singapore,Citizen,0.0,NaN
12,1595,2020-04-27,2020-04-08,82,M,Singapore,Citizen,0.0,NaN
13,9682,2020-04-27,2020-04-20,81,M,Singapore,Citizen,0.0,NaN
14,703,2020-04-30,2020-03-26,58,F,Singapore,Citizen,0.0,NaN
24,11714,2020-06-04,2020-04-22,41,M,China,Foreigner,0.0,NaN
37,67264,2021-08-01,2021-08-01,34,M,Ukraine,Foreigner,0.0,NaN
38,66894,2021-08-02,2021-07-29,58,F,Singapore,Citizen,0.0,NaN
45,67560,2021-08-16,NaT,64,M,Singapore,Citizen,0.0,"end-stage renal failure, ischaemic cardiomyopa..."
52,67918,2021-08-26,2021-08-07,80,M,Singapore,Citizen,0.0,NaN
61,77580,2021-09-19,2021-09-16,85,M,Singapore,Citizen,1.0,NaN
67,75271,2021-09-21,2021-09-13,50,M,Singapore,Citizen,0.0,NaN

In [53]:
#to create a new variable called "DaysBetween" to count the number of days between death date and COVID positive result
death_df_fil.insert(death_df_fil.columns.get_loc('Date_positive') + 1, 'DaysBetween', death_df_fil['Date_death'] - death_df_fil['Date_positive'])

In [54]:
death_df_fil.head()

,Case,Date_death,Date_positive,DaysBetween,Age,Gender,Nationality,Citizenship,Vaccine_no_dose,Medical_history
0,90,2020-03-21,2020-02-16,34 days,75,F,Singapore,Citizen,0.0,"chronic heart disease, hypertension"
1,212,2020-03-21,2020-03-14,7 days,64,M,Indonesia,Foreigner,0.0,heart disease
2,109,2020-03-29,2020-03-02,27 days,70,M,Singapore,Citizen,0.0,"hypertension, hyperlipidaemia"
3,476,2020-04-02,2020-03-22,11 days,68,M,Indonesia,Foreigner,0.0,"diabetes, hypertension"
4,918,2020-04-03,2020-03-31,3 days,86,F,Singapore,Citizen,0.0,NaN

For the cases with missing values in "Medical_history" column, we are going to assume that the case had no medical history. This may not always be true, and at MOH it is the duty of the officer to contact the close relatives of the case for verification. As an alternative, we will just assume such cases have no medical issues for the purpose of this project.

In [55]:
#to fill up the missing value for 'Medical History'
death_df_fil['Medical_history'] = death_df_fil['Medical_history'].fillna('0')

In [56]:
#to fill up the missing value for 'DaysBetween' and 'Date_positive' as this not something we could find proxy for
death_df_fil['Date_positive'] = death_df_fil['Date_positive'].fillna('NA')
death_df_fil['DaysBetween'] = death_df_fil['DaysBetween'].fillna('NA')

In [57]:
death_df_fil.isnull().sum()

Case               0
Date_death         0
Date_positive      0
DaysBetween        0
Age                0
Gender             0
Nationality        0
Citizenship        0
Vaccine_no_dose    0
Medical_history    0
dtype: int64

In [58]:
#to rename dataframe and only choose the top 75 deaths for our analysis
df_deaths = death_df_fil.head(75) 

#to see the changes in the size of dataframe before and after cleaning
print(df2.shape)
print()
print(df_deaths.shape)
print()
diff_rows = df2.shape[0] - df_deaths.shape[0]
print(diff_rows)
print()
diff_cols = df2.shape[1] - df_deaths.shape[1]
print(diff_cols)

(85, 12)

(75, 10)

10

2

### 3) Cleaning of Third DataFrame - based on the profiles of Covid Cases

In [59]:
#to display the first few rows of the 'profiles_df' DataFrame
profiles_df.head(20)

,case_id,age,gender,nationality,imported_local,place,public_healthcare_institution,status,date_of_confirmation,date_of_discharge,places_visited,residing_location,residing_postal_code,reference_url
0,Case 1,66,M,Chinese,Imported,Wuhan,Singapore General Hospital,Hospitalised,1/23/2020,-,NaN,Shangri-La Rasa Sentosa Resort & Spa,98970,https://www.moh.gov.sg/news-highlights/details...
1,Case 2,53,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/24/2020,2020-07-02 00:00:00,"Raffles Hospital, Tan Tock Seng Emergency Depa...","J8 hotel, 8 Townshend Road",207606,https://www.moh.gov.sg/news-highlights/details...
2,Case 3,37,M,Chinese,Imported,Wuhan,Singapore General Hospital,Hospitalised,1/24/2020,-,NaN,NaN,0,https://www.moh.gov.sg/news-highlights/details...
3,Case 4,36,M,Chinese,Imported,Wuhan,Sengkang General Hospital,Discharged,1/25/2020,2020-12-02 00:00:00,"USS, Vivocity",Village Hotel Sentosa,99951,https://www.moh.gov.sg/news-highlights/details...
4,Case 5,56,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,1/27/2020,-,Tan Tock Seng Hospital,Ceylon Road,429728,https://www.moh.gov.sg/news-highlights/details...
5,Case 6,56,M,Chinese,Imported,Wuhan,Changi General Hospital,Hospitalised,1/27/2020,-,Changi General Hospital,Pasir Ris Grove,518206,https://www.moh.gov.sg/news-highlights/details...
6,Case 7,35,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/27/2020,2020-04-02 00:00:00,Raffles Hospital,Marina Bay Sands (10 Bayfront Avenue),0,https://www.moh.gov.sg/news-highlights/details...
7,Case 8,56,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,1/28/2020,-,"Tan Tock Seng Hospital,The Life Church and Mis...",Lorong Lew Lian,531004,https://www.moh.gov.sg/news-highlights/details...
8,Case 9,56,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,1/29/2020,-,"Tan Tock Seng Hospital,The Life Church and Mis...",Lorong Lew Lian,531004,https://www.moh.gov.sg/news-highlights/details...
9,Case 10,56,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/29/2020,2020-09-02 00:00:00,Marina South Pier,NaN,0,https://www.moh.gov.sg/news-highlights/details...
10,Case 11,31,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/29/2020,2020-10-02 00:00:00,NaN,NaN,0,https://www.moh.gov.sg/news-highlights/details...
11,Case 12,37,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/29/2020,2020-12-02 00:00:00,"Orchard Road, Geylang, Tan Tock Seng Hospital","Village Hotel Sentosa (10 Artillery Avenue), H...",99951,https://www.moh.gov.sg/news-highlights/details...
12,Case 13,73,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/30/2020,2020-09-02 00:00:00,"Changi Airport, Jewel",Park Royal collection Pickering street(3 upper...,79333,https://www.moh.gov.sg/news-highlights/details...
13,Case 14,31,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/30/2020,2/17/2020,NaN,Jurong East Street 13,600116,https://www.moh.gov.sg/news-highlights/details...
14,Case 15,47,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/31/2020,2/17/2020,NaN,NaN,0,https://www.moh.gov.sg/news-highlights/details...
15,Case 16,38,M,Chinese,Imported,Wuhan,Singapore General Hospital,Hospitalised,1/31/2020,-,Singapore General Hospital,Nathan Road,248730,https://www.moh.gov.sg/news-highlights/details...
16,Case 17,47,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,1/31/2020,2020-11-02 00:00:00,NaN,NaN,0,https://www.moh.gov.sg/news-highlights/details...
17,Case 18,31,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,2020-01-02 00:00:00,-,NaN,Home Suite View Hotel (12 Lorong 12 Geylang),0,https://www.moh.gov.sg/news-highlights/details...
18,Case 19,28,F,Singapore,Local,Singapore,Singapore General Hospital,Hospitalised,2020-03-02 00:00:00,-,"Yong Thai Hang (24 Cavan Road), Tan Tock Seng ...",Jalan Bukit Merah,159456,https://www.moh.gov.sg/news-highlights/details...
19,Case 20,48,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-03-02 00:00:00,-,Yong Thai Hang (24 Cavan Road),Hougang Street 61,530685,https://www.moh.gov.sg/news-highlights/details...

In [60]:
#to show the size of the dataset (number of rows and columns)
print(profiles_df.shape) 

#to show the type and number of columns
print(profiles_df.columns)

(77, 14)
Index(['case_id', 'age', 'gender', 'nationality', 'imported_local', 'place',
       'public_healthcare_institution', 'status', 'date_of_confirmation',
       'date_of_discharge', 'places_visited', 'residing_location',
       'residing_postal_code', 'reference_url'],
      dtype='object')

In [61]:
#to view data types of the columns in the DataFrame
profiles_df.dtypes

case_id                          object
age                               int64
gender                           object
nationality                      object
imported_local                   object
place                            object
public_healthcare_institution    object
status                           object
date_of_confirmation             object
date_of_discharge                object
places_visited                   object
residing_location                object
residing_postal_code              int64
reference_url                    object
dtype: object

In [62]:
#to drop other columns that would not be meaningful for analysis (either because they are not needed or have a lot of missing values)
profiles_df_fil = profiles_df.drop(['reference_url', 'date_of_discharge'], axis=1)

In [63]:
#to change data type of "date_of_confirmation" from object to datetime type
profiles_df_fil['date_of_confirmation'] = pd.to_datetime(profiles_df_fil['date_of_confirmation'])

In [64]:
#to select numerical and categorical variables
numerical_columns2 = profiles_df_fil.select_dtypes(include=[int,float]).columns
categorical_columns2 = profiles_df_fil.select_dtypes('object').columns
datetime_columns2 = profiles_df_fil.select_dtypes('datetime').columns


#to count the number of numerical and categorical variables
print(len(numerical_columns2)) 
print(len(categorical_columns2))
print(len(datetime_columns2))

2
9
1

In [65]:
#to check for missing values for each column
profiles_df_fil.isnull().sum()

case_id                           0
age                               0
gender                            0
nationality                       0
imported_local                    0
place                             0
public_healthcare_institution     0
status                            0
date_of_confirmation              0
places_visited                   18
residing_location                15
residing_postal_code              0
dtype: int64

Since the recent places visited by the confirmed cases are stored as a list in the "places_visited" column, we need to first extract and perform text-analysis to identify the frequently visited places. 

These places will be considered the hot zones, and individuals who have visited these places will be identified first and placed under quarantine/isolation immediately to curb the spread of the virus.

In [66]:
#to calculate the count of places visited by confirmed cases so we can identify the frequently visited places
from collections import Counter

places_list = profiles_df_fil['places_visited'].tolist()

cleaned_list = []
for item in places_list:
    if isinstance(item, str):
        cleaned_list.extend(item.split(', '))

term_frequency = Counter(cleaned_list)

term_frequency_df = pd.DataFrame(list(term_frequency.items()), columns=['Term', 'Frequency'])
term_frequency_df = term_frequency_df.sort_values(by='Frequency', ascending=False)

pd.set_option('display.max_colwidth', 50)
pd.set_option('display.max_rows', None)
print(term_frequency_df)

                                                 Term  Frequency
62                    Grace Assembly of God (Tanglin)          5
63                Grace Assembly of God (Bukit Batok)          5
29                                           Malaysia          5
7                              Tan Tock Seng Hospital          4
51                        8 Seletar Aerospace Heights          3
60  Grace Assembly of God (Tanglin) (355 Tanglin R...          3
19                                 Hougang Polyclinic          3
16                     Yong Thai Hang (24 Cavan Road)          2
41              Ng Teng Fong General Hospital (NTFGH)          2
65                              Grace Assembly of God          2
35                                     Yong Thai Hang          2
68  Church of Christ the King (2221 Ang Mo Kio Ave...          2
70                     Government quarantine facility          2
28                              Grand Hyatt Singapore          2
79  God's Kingdom Bread of Life Church (37 Jalan P...          2
17        Tan Tock Seng Hospital Emergency Department          2
73                      Ng Teng Fong General Hospital          2
15                         Singapore General Hospital          2
2                                        Orchard Road          2
10  Tan Tock Seng Hospital,The Life Church and Mis...          2
3                                    Marina Bay Sands          2
8                             Changi General Hospital          2
13                                     Changi Airport          2
55                                       Chingay 2020          1
56    Resort World Sentosa Casino (8 Sentosa Gateway)          1
57                  Plaza Singapura (68 Orchard Road)          1
58                Star Vista (1 Vista Exchange Green)          1
66                  National University of Singapore           1
54               Certis Cisco Centre (20 Jalan Afifi)          1
61  Grace Assembly of God (Bukit Batok) (1 Bukit B...          1
87              Alexandra Hospital Urgent Care Centre          1
53                              Resorts World Sentosa          1
86  Aim Heng Car Services Pte Ltd (Woodlands Indus...          1
64  DBS Asia Central at Marina Bay Financial Centr...          1
85       Marina Bay Sands Casino (10 Bayfront Avenue)          1
59                Fusionopolis (1 Fusionopolis Place)          1
67                                        Pulau Bukom          1
80                                                NUH          1
84    God's Kingdom Bread of Life (37 Jalan Pemimpin)          1
69        Seletar Aerospace Heights Construction Site          1
71         Farrer Park Hospital Emergency Care Clinic          1
83                                      Fernvale Lane          1
82               HipVan Singapore (19 Kallang Avenue)          1
72      Mount Elizabeth Hospital Emergency Department          1
52                          Sengkang General Hospital          1
74                                 Pioneer Polyclinic          1
75  Legacy Office Supplies Pte Ltd (56 Senang Cres...          1
76                                                PUB          1
77              Marisson Hotel Bugis (103 Beach Road)          1
78                                        Taxi Driver          1
81  Bethany Presbyterian Church (344A Paya Lebar R...          1
0                                    Raffles Hospital          1
44                      Chinatown and Plaza Singapura          1
50                Mustafa Centre (145 Syed Alwi Road)          1
49                                   Bedok Polyclinic          1
26                  Far East Square (19 China Street)          1
25                Beo Crescent Market and Food Centre          1
24                                 Tiong Bahru Market          1
23                                  Tiong Bahru Plaza          1
22                       Pasir Panjang Hawker Centre           1
21  Diamond Industries Jewellery Company (Harbour ...          1
20                                        Jalan Besar          1
18                       Yong Thai Hang 24 Cavan Road          1
14                                              Jewel          1
12                                            Geylang          1
11                                  Marina South Pier          1
9                                   Raffles Hospital           1
6                                            Vivocity          1
5                                                 USS          1
4                                  Gardens by the Bay          1
27                        Junction 8 (9 Bishan Place)          1
30  The Life Church and Missions Singapore (146B P...          1
31                            Victoria Junior College          1
42                          Choa Chua Kang Polyclinic          1
48  Patâ€šÃ„Ã´s Schoolhouse Kovan (755 Upper Serangoon...          1
47              Braddell Heights Residents' Committee          1
46      Paya Lebar Methodist Church (5 Boundary Road)          1
45                             Grand Hyatt Singapore           1
1                  Tan Tock Seng Emergency Department          1
43             The Life Church and Missions Singapore          1
40           KK Women's and Children's Hospital (KKH)          1
32                              Parkway East Hospital          1
39                                        Johor Bahru          1
38                             Bukit Merah Polyclinic          1
37                       Hawker centre at Bukit Merah          1
36                                     Redhill Market          1
34     Sengkang General Hospital Emergency Department          1
33                                      Singapore Zoo          1
88         Hi-Yew Technology Pte Ltd (3031A Ubi Road)          1

In [67]:
#to create new dictionary to perform data cleaning so we can easily group together the common places
replace_dict = {
    'Old Grace Assembly of God (Tanglin) (355 Tanglin Road)': 'Grace Assembly of God (Tanglin)',
    'Yong Thai Hang (24 Cavan Road)': 'Yong Thai Hang',
    'Ng Teng Fong General Hospital (NTFGH)': 'Ng Teng Fong General Hospital',
    'Tan Tock Seng Hospital Emergency Department': 'Tan Tock Seng Hospital',
    'Grace Assembly of God (Bukit Batok) (1 Bukit Batok West Avenue 4)': 'Grace Assembly of God (Bukit Batok)',
    'Alexandra Hospital Urgent Care Centre': 'Alexandra Hospital',
    'Yong Thai Hang 24 Cavan Road': 'Yong Thai Hang',
    'Johor Bahru': 'Malaysia',
    'Sengkang General Hospital Emergency Department': 'Sengkang General Hospital',
    'Chinatown and Plaza Singapura': 'Plaza Singapura',
    'The Life Church and Missions Singapore (146B Paya Lebar Road)': 'The Life Church and Missions Singapore',
    'Tan Tock Seng Hospital,The Life Church and Missions Singapore (146B Paya Lebar Road)': 'The Life Church and Missions Singapore',
    'Resort World Sentosa Casino (8 Sentosa Gateway)': 'Resorts World Sentosa',
    'Grand Hyatt Singapore ': 'Grand Hyatt Singapore',
    '8 Seletar Aerospace Heights' : 'Seletar Aerospace Heights',
    'Seletar Aerospace Heights Construction Site' : 'Seletar Aerospace Heights',
    'Marina Bay Sands Casino (10 Bayfront Avenue)' : 'Resorts World Sentosa',
    'Jewel' : 'Changi Airport',
    'Tan Tock Seng Emergency Department' : 'Tan Tock Seng Hospital',
    'Grace Assembly of God (Tanglin) (355 Tanglin Road)' : 'Grace Assembly of God (Tanglin)',
    'Plaza Singapura (68 Orchard Road)' : 'Orchard Road', 
    'Plaza Singapura' : 'Orchard Road',
    'Raffles Hospital ' : 'Raffles Hospital'
}

In [68]:
#to perform data cleaning based on the dictionary and recalculate the counts
new_cleanedlist = [replace_dict[x] if x in replace_dict else x for x in cleaned_list]

term_frequency = Counter(new_cleanedlist)

term_frequency_df = pd.DataFrame(list(term_frequency.items()), columns=['Term', 'Frequency'])
term_frequency_df = term_frequency_df.sort_values(by='Frequency', ascending=False)

pd.set_option('display.max_colwidth', 60)
pd.set_option('display.max_rows', None)
print(term_frequency_df)

                                                           Term  Frequency
47                              Grace Assembly of God (Tanglin)          8
1                                        Tan Tock Seng Hospital          7
24                                                     Malaysia          6
48                          Grace Assembly of God (Bukit Batok)          6
13                                               Yong Thai Hang          5
33                                Ng Teng Fong General Hospital          4
8                        The Life Church and Missions Singapore          4
41                                    Seletar Aerospace Heights          4
23                                        Grand Hyatt Singapore          3
11                                               Changi Airport          3
2                                                  Orchard Road          3
14                                           Hougang Polyclinic          3
42                                        Resorts World Sentosa          3
50                                        Grace Assembly of God          2
53         Church of Christ the King (2221 Ang Mo Kio Avenue 8)          2
28                                    Sengkang General Hospital          2
54                               Government quarantine facility          2
0                                              Raffles Hospital          2
3                                              Marina Bay Sands          2
62       God's Kingdom Bread of Life Church (37 Jalan Pemimpin)          2
12                                   Singapore General Hospital          2
7                                       Changi General Hospital          2
61                                                  Taxi Driver          1
66                                                Fernvale Lane          1
44                                                 Chingay 2020          1
45                          Star Vista (1 Vista Exchange Green)          1
46                          Fusionopolis (1 Fusionopolis Place)          1
69                                           Alexandra Hospital          1
68    Aim Heng Car Services Pte Ltd (Woodlands Industrial Park)          1
67              God's Kingdom Bread of Life (37 Jalan Pemimpin)          1
49  DBS Asia Central at Marina Bay Financial Centre (12 Mari...          1
52                                                  Pulau Bukom          1
51                            National University of Singapore           1
60                        Marisson Hotel Bugis (103 Beach Road)          1
65                         HipVan Singapore (19 Kallang Avenue)          1
64           Bethany Presbyterian Church (344A Paya Lebar Road)          1
55                   Farrer Park Hospital Emergency Care Clinic          1
56                Mount Elizabeth Hospital Emergency Department          1
63                                                          NUH          1
57                                           Pioneer Polyclinic          1
43                         Certis Cisco Centre (20 Jalan Afifi)          1
59                                                          PUB          1
58          Legacy Office Supplies Pte Ltd (56 Senang Crescent)          1
35                                              Plaza Singapura          1
40                          Mustafa Centre (145 Syed Alwi Road)          1
21                            Far East Square (19 China Street)          1
4                                            Gardens by the Bay          1
5                                                           USS          1
6                                                      Vivocity          1
9                                             Marina South Pier          1
10                                                      Geylang          1
15                                                  Jalan Besar          1
16         Diamond Industries Jewellery Company (Harbour Drive)          1
17                                 Pasir Panjang Hawker Centre           1
18                                            Tiong Bahru Plaza          1
19                                           Tiong Bahru Market          1
20                          Beo Crescent Market and Food Centre          1
22                                  Junction 8 (9 Bishan Place)          1
39                                             Bedok Polyclinic          1
25                                      Victoria Junior College          1
26                                        Parkway East Hospital          1
27                                                Singapore Zoo          1
29                                               Redhill Market          1
30                                 Hawker centre at Bukit Merah          1
31                                       Bukit Merah Polyclinic          1
32                     KK Women's and Children's Hospital (KKH)          1
34                                    Choa Chua Kang Polyclinic          1
36                Paya Lebar Methodist Church (5 Boundary Road)          1
37                        Braddell Heights Residents' Committee          1
38         Patâ€šÃ„Ã´s Schoolhouse Kovan (755 Upper Serangoon Road)          1
70                   Hi-Yew Technology Pte Ltd (3031A Ubi Road)          1

In [69]:
#to highlight the top 5 frequently visited places to put in the dashboard
term_frequency_df = term_frequency_df.head(5)
term_frequency_df

                                   Term  Frequency
47      Grace Assembly of God (Tanglin)          8
1                Tan Tock Seng Hospital          7
24                             Malaysia          6
48  Grace Assembly of God (Bukit Batok)          6
13                       Yong Thai Hang          5

In [70]:
#to drop the "places_visited" column since we have already created a separate dataframe for it
profiles_df_fil.drop('places_visited', axis=1, inplace=True)

For the purpose of this analysis, we will only be looking at the first 75 cases and deaths.

In [71]:
#to choose the top 75 cases for our analysis (same as deaths)
profiles_df_fil = profiles_df_fil.head(75)
profiles_df_fil

,case_id,age,gender,nationality,imported_local,place,public_healthcare_institution,status,date_of_confirmation,residing_location,residing_postal_code
0,Case 1,66,M,Chinese,Imported,Wuhan,Singapore General Hospital,Hospitalised,2020-01-23,Shangri-La Rasa Sentosa Resort & Spa,98970
1,Case 2,53,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-24,"J8 hotel, 8 Townshend Road",207606
2,Case 3,37,M,Chinese,Imported,Wuhan,Singapore General Hospital,Hospitalised,2020-01-24,NaN,0
3,Case 4,36,M,Chinese,Imported,Wuhan,Sengkang General Hospital,Discharged,2020-01-25,Village Hotel Sentosa,99951
4,Case 5,56,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,2020-01-27,Ceylon Road,429728
5,Case 6,56,M,Chinese,Imported,Wuhan,Changi General Hospital,Hospitalised,2020-01-27,Pasir Ris Grove,518206
6,Case 7,35,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-27,Marina Bay Sands (10 Bayfront Avenue),0
7,Case 8,56,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,2020-01-28,Lorong Lew Lian,531004
8,Case 9,56,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,2020-01-29,Lorong Lew Lian,531004
9,Case 10,56,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-29,NaN,0
10,Case 11,31,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-29,NaN,0
11,Case 12,37,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-29,"Village Hotel Sentosa (10 Artillery Avenue), Hotel 81 Pr...",99951
12,Case 13,73,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-30,Park Royal collection Pickering street(3 upper Pickering...,79333
13,Case 14,31,M,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-30,Jurong East Street 13,600116
14,Case 15,47,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-31,NaN,0
15,Case 16,38,M,Chinese,Imported,Wuhan,Singapore General Hospital,Hospitalised,2020-01-31,Nathan Road,248730
16,Case 17,47,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-01-31,NaN,0
17,Case 18,31,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,2020-01-02,Home Suite View Hotel (12 Lorong 12 Geylang),0
18,Case 19,28,F,Singapore,Local,Singapore,Singapore General Hospital,Hospitalised,2020-03-02,Jalan Bukit Merah,159456
19,Case 20,48,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-03-02,Hougang Street 61,530685
20,Case 21,44,F,Indonesia,Local,Singapore,Singapore General Hospital,Hospitalised,2020-03-02,Jalan Bukit Merah,159456
21,Case 22,41,M,Singapore,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-03-02,NaN,0
22,Case 23,17,M,Singapore,Imported,Wuhan,National Centre for Infectious Disease,Hospitalised,2020-03-02,NaN,0
23,Case 24,32,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-01-02,Buangkok Green,532988
24,Case 25,40,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-04-02,Buangkok Green,532988
25,Case 26,42,F,Chinese,Imported,Wuhan,National Centre for Infectious Disease,Discharged,2020-04-02,NaN,79333
26,Case 27,45,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-05-02,Jalan Bukit Merah,159456
27,Case 28,0,M,Singapore,Local,Singapore,KK Women's and Children's Hospital,Hospitalised,2020-05-02,Jalan Bukit Merah,159456
28,Case 29,41,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-05-02,Mount Elizabeth Novena Hospital,329563
29,Case 30,27,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-06-02,Shunfu Road,570312
30,Case 31,53,M,Singapore,Local,Singapore,Changi General Hospital,Discharged,2020-01-02,Tampines Street 24,521222
31,Case 32,42,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-06-02,Elias Road,510625
32,Case 33,39,F,Singapore,Local,Singapore,Sengkang General Hospital,Hospitalised,2020-06-02,NaN,0
33,Case 34,40,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-07-02,Sin Ming Road,570022
34,Case 35,64,M,Singapore,Local,Singapore,Singapore General Hospital,Hospitalised,2020-07-02,Henderson Crescent,150103
35,Case 36,38,F,Singapore PR,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-07-02,Bukit Batok Street 31,659443
36,Case 37,53,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-07-02,Jurong East Street 32,600307
37,Case 38,52,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-08-02,Choa Chu Kang Avenue 3,680473
38,Case 39,51,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-08-02,Jurong West Central,648886
39,Case 40,36,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-08-02,Bedok North Street,460554
40,Case 41,71,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-08-02,Upper Serangoon Road,534645
41,Case 42,39,M,Bangladesh,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-08-02,The Leo Dormitory (25 Kaki Bukit Road),415812
42,Case 43,54,M,Singapore,Local,Singapore,Sengkang General Hospital,Hospitalised,2020-08-02,Fernvale Close,0
43,Case 44,37,M,Singapore,Local,Singapore,Khoo Teck Puat Hospital,Hospitalised,2020-09-02,Sembawang Drive,0
44,Case 45,2,F,Singapore,Imported,Wuhan,KK Women's and Children's Hospital,Discharged,2020-10-02,NaN,0
45,Case 46,35,M,Singapore PR,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-10-02,Johor Bahru,0
46,Case 47,39,M,Bangladesh,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-10-02,Veerasamy Road,0
47,Case 48,34,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-11-02,Bukit Batok Street 25,0
48,Case 49,46,M,Singapore,Local,Singapore,National University Hospital,Hospitalised,2020-11-02,Toh Guan Road,608571
49,Case 50,62,M,Singaproe,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-12-02,Mei Hwan Drive,0
50,Case 51,48,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-12-02,Bishan Street 13,0
51,Case 52,37,M,Bangladesh (Singapore Work Pass Holder),Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-12-02,Campbell Lane,0
52,Case 53,54,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-12-02,Hillview Avenue,0
53,Case 54,55,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,Ang Mo Kio Avenue 5,0
54,Case 55,30,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,Mei Hwan Drive,0
55,Case 56,30,M,Bangladesh (Singapore Work Pass Holder),Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,NaN,0
56,Case 57,26,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,Senja Road,0
57,Case 58,55,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,Jalan Kelichap,0
58,Case 59,61,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,Wilkinson Road,0
59,Case 60,51,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-13,Ang Mo Kio Ave 3,0
60,Case 61,57,M,Singapore,Local,Singapore,National University Hospital,Hospitalised,2020-02-13,Jurong West Street 64,0
61,Case 62,44,F,Singapore,Local,Singapore,Singapore General Hospital,Hospitalised,2020-02-13,Tanjong Pagar Road,0
62,Case 63,54,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-14,Potong Pasir Avenue 3,0
63,Case 64,50,M,Singapore,Local,Singapore,National University Hospital,Hospitalised,2020-02-14,Jurong West Street 81,0
64,Case 65,61,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Discharged,2020-02-14,Mei Hwan Drive,0
65,Case 66,28,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-14,Mei Hwan Drive,0
66,Case 67,56,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-14,Jurong West Street 64,0
67,Case 68,79,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-14,Mei Hwan Drive,0
68,Case 69,26,M,Bangladesh (Singapore Work Pass Holder),Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-15,NaN,0
69,Case 70,27,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-15,Mei Hwan Drive,0
70,Case 71,25,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-15,Fernvale Road,0
71,Case 72,40,M,Chinese (Singapore Work Pass Holder),Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-15,Woodlands Crescent,0
72,Case 73,43,M,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-15,Lorong 8 Toa Payoh,0
73,Case 74,29,M,Singapore,Local,Singapore,Alexandra Hospital,Hospitalised,2020-02-15,Mei Ling Street,0
74,Case 75,71,F,Singapore,Local,Singapore,National Centre for Infectious Disease,Hospitalised,2020-02-16,NaN,0

In [72]:
#to clean the "nationality" column and make sure the values are standardized
profiles_df_fil['nationality'] = profiles_df_fil['nationality'].replace({'Chinese (Singapore Work Pass Holder)': 'Chinese'})
profiles_df_fil['nationality'] = profiles_df_fil['nationality'].replace({'Bangladesh (Singapore Work Pass Holder)': 'Bangladesh'})

In [73]:
#to convert "residing_postal_code" from float type to integer type
profiles_df_fil['residing_postal_code'] = profiles_df_fil['residing_postal_code'].astype(float).astype('Int64')

In [74]:
#to convert missing values to 0 for "residing_postal_code"
profiles_df_fil['residing_postal_code'] = profiles_df_fil['residing_postal_code'].replace(0, float('nan'))

In [75]:
#to convert missing values to 0 for "residing_location"
profiles_df_fil.loc[profiles_df_fil['residing_location'].isna(), 'residing_postal_code'] = 0

In [76]:
#to check for missing values again
profiles_df_fil.isnull().sum()

case_id                           0
age                               0
gender                            0
nationality                       0
imported_local                    0
place                             0
public_healthcare_institution     0
status                            0
date_of_confirmation              0
residing_location                13
residing_postal_code             30
dtype: int64

For the rows where the values in postal code is missing but the location address is present, we have done research to find a postal code in this area. Since the full address is not available as most of the values only have partial info, we will use proxy postal code somewhere near the area of the location.

Usually, at work we will contact and clarify the address with the case. However, for the purpose of our project, we will just use the proxy postal code identified based on google research.

In [77]:
#to convert postal code data type to string type
profiles_df_fil['residing_postal_code'] = profiles_df_fil['residing_postal_code'].astype(str)

#to fill in the missing postal code based on residing location address and google search
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Mei Ling Street', 'residing_postal_code'] = '140150'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Lorong 8 Toa Payoh', 'residing_postal_code'] = '310220'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Woodlands Crescent', 'residing_postal_code'] = '732787'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Fernvale Road', 'residing_postal_code'] = '797637'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Mei Hwan Drive', 'residing_postal_code'] = '568365'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Jurong West Street 64', 'residing_postal_code'] = '640662'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Jurong West Street 81', 'residing_postal_code'] = '640848'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Potong Pasir Avenue 3', 'residing_postal_code'] = '350136'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Tanjong Pagar Road', 'residing_postal_code'] = '088520'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Ang Mo Kio Ave 3', 'residing_postal_code'] = '560311'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Wilkinson Road', 'residing_postal_code'] = '436716'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Jalan Kelichap', 'residing_postal_code'] = '538180'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Senja Road', 'residing_postal_code'] = '670629'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Ang Mo Kio Ave 5', 'residing_postal_code'] = '560520'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Hillview Avenue', 'residing_postal_code'] = '669562'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Campbell Lane', 'residing_postal_code'] = '209888'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Bishan Street 13', 'residing_postal_code'] = '570158'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Bukit Batok Street 25', 'residing_postal_code'] = '653288'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Veerasamy Road', 'residing_postal_code'] = '207332'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Johor Bahru', 'residing_postal_code'] = '80100'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Sembawang Drive', 'residing_postal_code'] = '757715'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Fernvale Close', 'residing_postal_code'] = '797475'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Home Suite View Hotel (12 Lorong 12 Geylang)', 'residing_postal_code'] = '398993'
profiles_df_fil.loc[profiles_df_fil['residing_location'] == 'Marina Bay Sands (10 Bayfront Avenue)', 'residing_postal_code'] = '018956'

In [78]:
profiles_df_fil.isnull().sum()

case_id                           0
age                               0
gender                            0
nationality                       0
imported_local                    0
place                             0
public_healthcare_institution     0
status                            0
date_of_confirmation              0
residing_location                13
residing_postal_code              0
dtype: int64

In [79]:
#to rename dataframe
df_profiles = profiles_df_fil

In [80]:
#to download our cleaned dataset as excel files
df_cases.to_excel('cases.xlsx', index=False)
df_deaths.to_excel('deaths.xlsx', index=False)
df_profiles.to_excel('caseprofiles.xlsx', index=False)
term_frequency_df.to_excel('location.xlsx' , index=False)

<ipython-input-80-77da86473baa>:2: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  df_cases.to_excel('cases.xlsx', index=False)
<ipython-input-80-77da86473baa>:3: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  df_deaths.to_excel('deaths.xlsx', index=False)
<ipython-input-80-77da86473baa>:4: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  df_profiles.to_excel('caseprofiles.xlsx', index=False)
<ipython-input-80-77da86473baa>:5: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  term_frequency_df.to_excel('location.xlsx' , index=False)